import { access, mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { pathToFileURL } from "node:url";

import { findRepoRoot } from "../triggers/catalog-generator.js";

/**
 * Per-provider **writeback path** templates — the canonical Relayfile-mount
 * paths an agent writes a draft JSON file to in order to trigger a provider
 * mutation (create issue, comment, post message). Each adapter's
 * `resources.ts` is the source of truth: the same `{ name, path }` data the
 * writeback worker's `classifyWrite` matches incoming drafts against. This
 * catalog harvests it cross-provider so a single consumer dependency
 * (`@relayfile/adapter-core/writeback-paths`) can resolve a draft path from
 * `(provider, resource, params)` without taking a dependency on every
 * `@relayfile/adapter-<provider>` package.
 */
export interface WritebackResourcePath {
  /** Path template with `{param}` placeholders, e.g. `/linear/issues/{issueId}/comments`. */
  path: string;
  /** Placeholder names in template order, e.g. `["issueId"]`. */
  params: string[];
}

/**
 * provider → resource name → path template variants.
 *
 * A resource `name` is NOT unique within an adapter: the same entity is mounted
 * at several paths (e.g. notion `pages` →
 * `/notion/databases/{databaseId}/pages`, `/notion/pages/{pageId}.json`, …).
 * Every distinct template is kept; the resolver disambiguates by the exact set
 * of params supplied. Collapsing to one path per name would silently drop valid
 * writeback targets.
 */
export type WritebackPathCatalog = Record<string, Record<string, WritebackResourcePath[]>>;

export interface AdapterWithoutWritebackPaths {
  packageName: string;
  packagePath: string;
  provider: string;
  reason: string;
}

export interface WritebackPathCatalogGeneration {
  catalog: WritebackPathCatalog;
  adaptersWithoutWritebackPaths: AdapterWithoutWritebackPaths[];
}

export interface WriteWritebackPathCatalogOptions {
  check?: boolean;
  repoRoot?: string;
}

interface AdapterPackage {
  dir: string;
  packageName: string;
  provider: string;
  relativePath: string;
}

interface AdapterResource {
  name: string;
  path: string;
}

const GENERATED_HEADER = `/**
 * Generated by \`adapter-core writeback-paths generate\`.
 *
 * Writeback path templates are emitted verbatim from each adapter's
 * \`resources.ts\` (\`{ name, path }\`) — the same source the writeback worker's
 * \`classifyWrite\` routes drafts against. A consumer resolves a concrete draft
 * path with \`writebackPath(provider, resource, params)\`.
 */
`;

const NON_ADAPTER_PACKAGES = new Set([
  "@relayfile/adapter-core",
  "@relayfile/webhook-server",
  "@relayfile/relay-helpers"
]);

export async function generateWritebackPathCatalog(
  repoRoot?: string
): Promise<WritebackPathCatalogGeneration> {
  repoRoot = repoRoot ? resolve(repoRoot) : await findRepoRoot();
  const packages = await listAdapterPackages(repoRoot);
  const entries: Array<{ provider: string; resources: AdapterResource[] }> = [];
  const adaptersWithoutWritebackPaths: AdapterWithoutWritebackPaths[] = [];

  for (const adapterPackage of packages) {
    const { resources, error } = await readAdapterResources(adapterPackage);
    if (resources.length > 0) {
      entries.push({ provider: adapterPackage.provider, resources });
      continue;
    }
    adaptersWithoutWritebackPaths.push({
      packageName: adapterPackage.packageName,
      packagePath: adapterPackage.relativePath,
      provider: adapterPackage.provider,
      reason: error ?? "No resources.ts with writeback path templates",
    });
  }

  return {
    catalog: sortCatalog(entries),
    adaptersWithoutWritebackPaths: adaptersWithoutWritebackPaths.sort(compareByPackagePath),
  };
}

export async function writeWritebackPathCatalog(
  options: WriteWritebackPathCatalogOptions = {}
): Promise<WritebackPathCatalogGeneration> {
  const repoRoot = options.repoRoot ? resolve(options.repoRoot) : await findRepoRoot();
  const generation = await generateWritebackPathCatalog(repoRoot);
  const paths = writebackPathCatalogPaths(repoRoot);
  const expectedFiles = new Map([
    [paths.catalogJson, renderJson(generation.catalog)],
    [paths.withoutJson, renderJson(generation.adaptersWithoutWritebackPaths)],
    [paths.catalogTs, renderWritebackPathCatalogModule(generation)],
  ]);

  if (options.check) {
    const mismatches: string[] = [];
    for (const [filePath, expected] of expectedFiles) {
      let actual = "";
      try {
        actual = await readFile(filePath, "utf8");
      } catch {
        mismatches.push(relative(repoRoot, filePath));
        continue;
      }
      // Normalize line endings: a CRLF checkout (Windows, no enforced
      // `.gitattributes`) must not read as a false out-of-sync mismatch.
      if (normalizeEol(actual) !== normalizeEol(expected)) {
        mismatches.push(relative(repoRoot, filePath));
      }
    }
    if (mismatches.length > 0) {
      throw new Error(
        [
          "Writeback-path catalog is out of sync.",
          "To fix, run the following command from the repo root:",
          "",
          "  npx adapter-core writeback-paths generate",
          "",
          "  # or, if the package is built locally:",
          "  node packages/core/dist/src/cli.js writeback-paths generate",
          "",
          `Stale files: ${mismatches.join(", ")}`,
        ].join("\n")
      );
    }
    return generation;
  }

  for (const [filePath, contents] of expectedFiles) {
    await mkdir(dirname(filePath), { recursive: true });
    await writeFile(filePath, contents);
  }

  return generation;
}

export function writebackPathCatalogPaths(repoRoot: string): {
  catalogJson: string;
  withoutJson: string;
  catalogTs: string;
} {
  const dir = join(repoRoot, "packages", "core", "src", "writeback-paths");
  return {
    catalogJson: join(dir, "catalog.generated.json"),
    withoutJson: join(dir, "adapters-without-writeback-paths.generated.json"),
    catalogTs: join(dir, "catalog.generated.ts"),
  };
}

export function renderWritebackPathCatalogModule(generation: WritebackPathCatalogGeneration): string {
  return `${GENERATED_HEADER}
export const WRITEBACK_PATH_CATALOG = ${renderInlineJson(generation.catalog)} as const satisfies Record<
  string,
  Record<string, readonly { path: string; params: readonly string[] }[]>
>;

export const ADAPTERS_WITHOUT_WRITEBACK_PATHS = ${renderInlineJson(generation.adaptersWithoutWritebackPaths)} as const;

export type WritebackProvider = keyof typeof WRITEBACK_PATH_CATALOG;
export type WritebackResource<P extends WritebackProvider> =
  keyof (typeof WRITEBACK_PATH_CATALOG)[P];
`;
}

/**
 * Read an adapter's writeback resources. Prefers the built `resources.js`
 * (a plain `{ name, path }[]` array — the same module `classifyWrite`
 * consumes); falls back to regex-parsing the `resources.ts` source so the
 * catalog still generates when an adapter is unbuilt.
 */
async function readAdapterResources(
  adapterPackage: AdapterPackage
): Promise<{ resources: AdapterResource[]; error?: string }> {
  const builtEntryPoint = await firstExistingPath([
    join(adapterPackage.dir, "dist", "resources.js"),
    join(adapterPackage.dir, "dist", "src", "resources.js"),
  ]);

  let importError: string | undefined;
  if (builtEntryPoint) {
    try {
      const moduleExports = (await import(pathToFileURL(builtEntryPoint).href)) as {
        resources?: unknown;
      };
      const resources = normalizeResources(moduleExports.resources);
      if (resources.length > 0) {
        return { resources };
      }
    } catch (error) {
      // Remember the import failure so it surfaces as the adapter's reason
      // instead of a generic "no resources" message — a swallowed import
      // error otherwise hides a real build/runtime problem.
      importError = `Could not import built adapter resources: ${errorMessage(error)}`;
    }
  }

  const sourceResources = await readResourcesFromSource(
    join(adapterPackage.dir, "src", "resources.ts")
  );
  if (sourceResources.length > 0) {
    return { resources: sourceResources };
  }

  return { resources: [], error: importError };
}

function normalizeResources(value: unknown): AdapterResource[] {
  if (!Array.isArray(value)) {
    return [];
  }
  const out: AdapterResource[] = [];
  for (const entry of value) {
    if (!isRecord(entry)) continue;
    const { name, path } = entry;
    if (typeof name === "string" && name.length > 0 && typeof path === "string" && path.length > 0) {
      out.push({ name, path });
    }
  }
  return out;
}

async function readResourcesFromSource(entryPoint: string): Promise<AdapterResource[]> {
  let contents: string;
  try {
    contents = await readFile(entryPoint, "utf8");
  } catch {
    return [];
  }
  // Match `name: "x"` immediately followed by `path: "/y"` within each
  // resource literal. `name` always precedes `path` in the generated file.
  const pattern = /name:\s*["']([^"']+)["']\s*,\s*path:\s*["']([^"']+)["']/gu;
  const out: AdapterResource[] = [];
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(contents)) !== null) {
    out.push({ name: match[1], path: match[2] });
  }
  return out;
}

function sortCatalog(
  entries: Array<{ provider: string; resources: AdapterResource[] }>
): WritebackPathCatalog {
  // provider → name → (path → variant). The inner map dedupes by path so an
  // exact (name, path) repeat collapses, while genuinely distinct templates
  // sharing a name are all retained (notion `pages`, asana `sections`, …).
  const catalog = new Map<string, Map<string, Map<string, WritebackResourcePath>>>();
  for (const entry of entries) {
    const byName = catalog.get(entry.provider) ?? new Map<string, Map<string, WritebackResourcePath>>();
    for (const resource of entry.resources) {
      const byPath = byName.get(resource.name) ?? new Map<string, WritebackResourcePath>();
      if (!byPath.has(resource.path)) {
        byPath.set(resource.path, { path: resource.path, params: extractParams(resource.path) });
      }
      byName.set(resource.name, byPath);
    }
    catalog.set(entry.provider, byName);
  }
  return Object.fromEntries(
    [...catalog.entries()]
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([provider, byName]) => [
        provider,
        Object.fromEntries(
          [...byName.entries()]
            .sort(([left], [right]) => left.localeCompare(right))
            .map(([name, byPath]) => [
              name,
              [...byPath.values()].sort((left, right) => left.path.localeCompare(right.path)),
            ])
        ),
      ])
  );
}

function normalizeEol(value: string): string {
  return value.replace(/\r\n/gu, "\n");
}

/** Placeholder names in template order, e.g. `/x/{a}/y/{b}` → `["a","b"]`. */
function extractParams(template: string): string[] {
  return [...template.matchAll(/\{([^}]+)\}/gu)].map((match) => match[1]);
}

async function listAdapterPackages(repoRoot: string): Promise<AdapterPackage[]> {
  const packagesDir = join(repoRoot, "packages");
  const names = await readdir(packagesDir);
  const packages: AdapterPackage[] = [];

  for (const name of names.sort()) {
    const dir = join(packagesDir, name);
    const packageJsonPath = join(dir, "package.json");
    let packageJson: { name?: string };
    try {
      packageJson = JSON.parse(await readFile(packageJsonPath, "utf8")) as { name?: string };
    } catch {
      continue;
    }
    // Only @relayfile/* packages are adapters. Skip other scopes (e.g.
    // @agentworkforce/persona-* data packages) so they are not scanned as
    // adapters and listed in the adapters-without-known-* catalogs.
    if (
      !packageJson.name ||
      !packageJson.name.startsWith("@relayfile/") ||
      NON_ADAPTER_PACKAGES.has(packageJson.name)
    ) {
      continue;
    }
    packages.push({
      dir,
      packageName: packageJson.name,
      provider: inferProviderSlug(packageJson.name, name),
      relativePath: relative(repoRoot, dir),
    });
  }

  return packages;
}

function inferProviderSlug(packageName: string, directoryName: string): string {
  if (packageName.startsWith("@relayfile/adapter-")) {
    return packageName.slice("@relayfile/adapter-".length);
  }
  if (packageName.startsWith("@relayfile/")) {
    return packageName.slice("@relayfile/".length);
  }
  return directoryName;
}

async function firstExistingPath(paths: string[]): Promise<string | undefined> {
  for (const path of paths) {
    try {
      await access(path);
      return path;
    } catch {
      // Try the next candidate.
    }
  }
  return undefined;
}

function compareByPackagePath(
  left: { packagePath: string; provider: string },
  right: { packagePath: string; provider: string }
): number {
  return left.packagePath.localeCompare(right.packagePath) || left.provider.localeCompare(right.provider);
}

function renderJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function renderInlineJson(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object";
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
