import { access, mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import YAML from "yaml";

import { findRepoRoot } from "../triggers/catalog-generator.js";

/**
 * Per-provider connection **scope** keys — the user-facing filter params a
 * persona may set under `integrations.<provider>.scope` (e.g. github →
 * `owner`/`repo`). Distinct from infra config (tokens, connectionId) and from
 * trigger event names. The cloud adapter decides what each key means; this
 * catalog just enumerates the declared keys per provider so persona authoring
 * can autocomplete + lint them.
 */
export type ScopeCatalog = Record<string, string[]>;

export interface AdapterWithoutKnownScopes {
  packageName: string;
  packagePath: string;
  provider: string;
  reason: string;
}

export interface ScopeCatalogSource {
  packageName: string;
  packagePath: string;
  provider: string;
  source: "mapping.scopes" | "supportedScopes";
}

export interface ScopeCatalogGeneration {
  catalog: ScopeCatalog;
  sources: ScopeCatalogSource[];
  adaptersWithoutKnownScopes: AdapterWithoutKnownScopes[];
}

export interface WriteScopeCatalogOptions {
  check?: boolean;
  repoRoot?: string;
}

interface AdapterPackage {
  dir: string;
  packageName: string;
  provider: string;
  relativePath: string;
}

const GENERATED_HEADER = `/**
 * Generated by \`adapter-core scopes generate\`.
 *
 * Scope keys are emitted verbatim from adapter supportedScopes() methods or
 * mapping.yaml \`scopes:\` keys. They name the per-provider connection filters
 * a persona may set under \`integrations.<provider>.scope\`.
 */
`;

const NON_ADAPTER_PACKAGES = new Set(["@relayfile/adapter-core", "@relayfile/webhook-server"]);

export async function generateScopeCatalog(repoRoot?: string): Promise<ScopeCatalogGeneration> {
  repoRoot = repoRoot ? resolve(repoRoot) : await findRepoRoot();
  const packages = await listAdapterPackages(repoRoot);
  const entries: Array<{ provider: string; keys: string[] }> = [];
  const sources: ScopeCatalogSource[] = [];
  const adaptersWithoutKnownScopes: AdapterWithoutKnownScopes[] = [];

  for (const adapterPackage of packages) {
    const mappingScopes = await readMappingScopeKeys(repoRoot, adapterPackage);
    const supportedScopes = await readSupportedScopes(adapterPackage);
    let hasKnownScopes = false;

    if (supportedScopes.keys.length > 0) {
      entries.push({ provider: supportedScopes.provider, keys: supportedScopes.keys });
      sources.push({
        packageName: adapterPackage.packageName,
        packagePath: adapterPackage.relativePath,
        provider: supportedScopes.provider,
        source: "supportedScopes",
      });
      hasKnownScopes = true;
    }

    if (mappingScopes.length > 0) {
      const provider = supportedScopes.keys.length > 0 ? supportedScopes.provider : adapterPackage.provider;
      entries.push({ provider, keys: mappingScopes });
      sources.push({
        packageName: adapterPackage.packageName,
        packagePath: adapterPackage.relativePath,
        provider,
        source: "mapping.scopes",
      });
      hasKnownScopes = true;
    }

    if (hasKnownScopes) {
      continue;
    }

    adaptersWithoutKnownScopes.push({
      packageName: adapterPackage.packageName,
      packagePath: adapterPackage.relativePath,
      provider: adapterPackage.provider,
      reason:
        supportedScopes.error ??
        "No supportedScopes() implementation and no mapping.yaml scopes block",
    });
  }

  return {
    catalog: sortCatalog(entries),
    sources: sources.sort(compareByPackagePath),
    adaptersWithoutKnownScopes: adaptersWithoutKnownScopes.sort(compareByPackagePath),
  };
}

export async function writeScopeCatalog(
  options: WriteScopeCatalogOptions = {}
): Promise<ScopeCatalogGeneration> {
  const repoRoot = options.repoRoot ? resolve(options.repoRoot) : await findRepoRoot();
  const generation = await generateScopeCatalog(repoRoot);
  const paths = scopeCatalogPaths(repoRoot);
  const expectedFiles = new Map([
    [paths.catalogJson, renderJson(generation.catalog)],
    [paths.noScopeJson, renderJson(generation.adaptersWithoutKnownScopes)],
    [paths.catalogTs, renderScopeCatalogModule(generation)],
  ]);

  if (options.check) {
    const mismatches: string[] = [];
    for (const [filePath, expected] of expectedFiles) {
      let actual = "";
      try {
        actual = await readFile(filePath, "utf8");
      } catch {
        mismatches.push(relative(repoRoot, filePath));
        continue;
      }
      if (actual !== expected) {
        mismatches.push(relative(repoRoot, filePath));
      }
    }
    if (mismatches.length > 0) {
      throw new Error(
        `Scope catalog is out of sync. Run \`adapter-core scopes generate\`. Stale files: ${mismatches.join(", ")}`
      );
    }
    return generation;
  }

  for (const [filePath, contents] of expectedFiles) {
    await mkdir(dirname(filePath), { recursive: true });
    await writeFile(filePath, contents);
  }

  return generation;
}

export function scopeCatalogPaths(repoRoot: string): {
  catalogJson: string;
  noScopeJson: string;
  catalogTs: string;
} {
  const scopeDir = join(repoRoot, "packages", "core", "src", "scopes");
  return {
    catalogJson: join(scopeDir, "catalog.generated.json"),
    noScopeJson: join(scopeDir, "adapters-without-known-scopes.generated.json"),
    catalogTs: join(scopeDir, "catalog.generated.ts"),
  };
}

export function renderScopeCatalogModule(generation: ScopeCatalogGeneration): string {
  return `${GENERATED_HEADER}
export const KNOWN_SCOPE_CATALOG = ${renderInlineJson(generation.catalog)} as const satisfies Record<
  string,
  readonly string[]
>;

export const ADAPTERS_WITHOUT_KNOWN_SCOPES = ${renderInlineJson(generation.adaptersWithoutKnownScopes)} as const;

export type KnownScopeProviderName = keyof typeof KNOWN_SCOPE_CATALOG;
export type KnownScopeKey<P extends KnownScopeProviderName> =
  (typeof KNOWN_SCOPE_CATALOG)[P][number];
`;
}

async function listAdapterPackages(repoRoot: string): Promise<AdapterPackage[]> {
  const packagesDir = join(repoRoot, "packages");
  const names = await readdir(packagesDir);
  const packages: AdapterPackage[] = [];

  for (const name of names.sort()) {
    const dir = join(packagesDir, name);
    const packageJsonPath = join(dir, "package.json");
    let packageJson: { name?: string };
    try {
      packageJson = JSON.parse(await readFile(packageJsonPath, "utf8")) as { name?: string };
    } catch {
      continue;
    }
    if (!packageJson.name || NON_ADAPTER_PACKAGES.has(packageJson.name)) {
      continue;
    }
    packages.push({
      dir,
      packageName: packageJson.name,
      provider: inferProviderSlug(packageJson.name, name),
      relativePath: relative(repoRoot, dir),
    });
  }

  return packages;
}

async function readSupportedScopes(
  adapterPackage: AdapterPackage
): Promise<{ keys: string[]; provider: string; error?: string }> {
  const sourceEntryPoint = join(adapterPackage.dir, "src", "index.ts");
  const sourceScopes = await readSupportedScopesFromSource(sourceEntryPoint);
  const builtEntryPoint = await firstExistingPath([
    join(adapterPackage.dir, "dist", "index.js"),
    join(adapterPackage.dir, "dist", "src", "index.js"),
  ]);

  if (builtEntryPoint) {
    const supportedScopes = await readSupportedScopesFromModule(adapterPackage, builtEntryPoint);
    if (supportedScopes.keys.length > 0) {
      return supportedScopes;
    }
  }

  if (sourceScopes.length > 0) {
    return { keys: sourceScopes, provider: adapterPackage.provider };
  }

  if (!builtEntryPoint && !(await pathExists(sourceEntryPoint))) {
    return {
      keys: [],
      provider: adapterPackage.provider,
      error: "No adapter entrypoint at dist/index.js, dist/src/index.js, or src/index.ts",
    };
  }

  return { keys: [], provider: adapterPackage.provider };
}

async function readSupportedScopesFromModule(
  adapterPackage: AdapterPackage,
  entryPoint: string
): Promise<{ keys: string[]; provider: string }> {
  let moduleExports: Record<string, unknown>;
  try {
    moduleExports = (await import(pathToFileURL(entryPoint).href)) as Record<string, unknown>;
  } catch {
    return { keys: [], provider: adapterPackage.provider };
  }

  const candidates = Object.entries(moduleExports)
    .filter(([, value]) => hasSupportedScopesPrototype(value))
    .sort(([left], [right]) => left.localeCompare(right)) as Array<
    [string, new (...args: never[]) => { name?: unknown; supportedScopes(): string[] }]
  >;

  for (const [, Candidate] of candidates) {
    const instance = instantiateAdapter(Candidate);
    if (!instance) {
      continue;
    }
    let keys: unknown;
    try {
      keys = instance.supportedScopes();
    } catch {
      continue;
    }
    const normalized = normalizeKeys(keys);
    if (normalized.length > 0) {
      return {
        keys: normalized,
        provider: typeof instance.name === "string" && instance.name ? instance.name : adapterPackage.provider,
      };
    }
  }

  return { keys: [], provider: adapterPackage.provider };
}

async function readSupportedScopesFromSource(entryPoint: string): Promise<string[]> {
  let contents: string;
  try {
    contents = await readFile(entryPoint, "utf8");
  } catch {
    return [];
  }

  const supportedScopesMethod =
    /\bsupportedScopes\s*\([^)]*\)\s*(?::[^{]+)?\{\s*return\s*\[([\s\S]*?)\]\s*;?\s*\}/u.exec(contents);
  if (!supportedScopesMethod) {
    return [];
  }

  const keys = new Set<string>();
  const stringLiteral = /["']([^"']+)["']/gu;
  let match: RegExpExecArray | null;
  while ((match = stringLiteral.exec(supportedScopesMethod[1] ?? "")) !== null) {
    keys.add(match[1]);
  }
  return [...keys].sort();
}

async function readMappingScopeKeys(repoRoot: string, adapterPackage: AdapterPackage): Promise<string[]> {
  const packageKeys = await readMappingScopeKeysFromDir(adapterPackage.dir);
  if (packageKeys.length > 0) {
    return packageKeys;
  }
  const coreMappingDir = join(repoRoot, "packages", "core", "mappings");
  return readMappingScopeKeysFromFiles([join(coreMappingDir, `${adapterPackage.provider}.mapping.yaml`)]);
}

async function readMappingScopeKeysFromDir(packageDir: string): Promise<string[]> {
  const filenames = (await readdir(packageDir)).filter((name) => name.endsWith(".mapping.yaml")).sort();
  return readMappingScopeKeysFromFiles(filenames.map((filename) => join(packageDir, filename)));
}

async function readMappingScopeKeysFromFiles(paths: string[]): Promise<string[]> {
  const keys = new Set<string>();
  for (const path of paths) {
    let contents: string;
    try {
      contents = await readFile(path, "utf8");
    } catch {
      continue;
    }
    const parsed = YAML.parse(contents) as { scopes?: unknown } | null;
    if (!parsed) continue;
    // Accept either a list (`scopes: [owner, repo]`) or a map keyed by name.
    if (Array.isArray(parsed.scopes)) {
      for (const key of parsed.scopes) if (typeof key === "string") keys.add(key);
    } else if (isRecord(parsed.scopes)) {
      for (const key of Object.keys(parsed.scopes)) keys.add(key);
    }
  }
  return [...keys].sort();
}

async function firstExistingPath(paths: string[]): Promise<string | undefined> {
  for (const path of paths) {
    if (await pathExists(path)) {
      return path;
    }
  }
  return undefined;
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

function instantiateAdapter(
  Candidate: new (...args: never[]) => { name?: unknown; supportedScopes(): string[] }
): { name?: unknown; supportedScopes(): string[] } | undefined {
  const client = createClientStub();
  const provider = createProviderStub();
  const attempts: unknown[][] = [
    [client, provider, {}],
    [provider, {}],
    [client, {}],
    [client, provider],
    [provider],
    [client],
    [{}],
    [],
  ];

  for (const args of attempts) {
    try {
      return new Candidate(...(args as never[]));
    } catch {
      // Try the next common adapter constructor shape.
    }
  }

  return undefined;
}

function createClientStub(): Record<string, unknown> {
  return {
    async deleteFile() {
      return undefined;
    },
    getWrittenRevision() {
      return undefined;
    },
    async readFile() {
      return undefined;
    },
    async writeFile() {
      return {};
    },
  };
}

function createProviderStub(): Record<string, unknown> {
  return {
    name: "scope-catalog-generator",
    async proxy() {
      return { status: 200, headers: {}, body: null };
    },
    async healthCheck() {
      return { ok: true };
    },
  };
}

function hasSupportedScopesPrototype(
  value: unknown
): value is new (...args: never[]) => { name?: unknown; supportedScopes(): string[] } {
  return (
    typeof value === "function" &&
    isRecord((value as { prototype?: unknown }).prototype) &&
    typeof (value as { prototype: Record<string, unknown> }).prototype.supportedScopes === "function"
  );
}

function normalizeKeys(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }
  return [...new Set(value.filter((key): key is string => typeof key === "string" && key.length > 0))].sort();
}

function sortCatalog(entries: Array<{ provider: string; keys: string[] }>): ScopeCatalog {
  const catalog = new Map<string, Set<string>>();
  for (const entry of entries) {
    const existing = catalog.get(entry.provider) ?? new Set<string>();
    for (const key of entry.keys) existing.add(key);
    catalog.set(entry.provider, existing);
  }
  return Object.fromEntries(
    [...catalog.entries()]
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([provider, keys]) => [provider, [...keys].sort()])
  );
}

function inferProviderSlug(packageName: string, directoryName: string): string {
  if (packageName.startsWith("@relayfile/adapter-")) {
    return packageName.slice("@relayfile/adapter-".length);
  }
  if (packageName.startsWith("@relayfile/")) {
    return packageName.slice("@relayfile/".length);
  }
  return directoryName;
}

function compareByPackagePath(
  left: { packagePath: string; provider: string },
  right: { packagePath: string; provider: string }
): number {
  return left.packagePath.localeCompare(right.packagePath) || left.provider.localeCompare(right.provider);
}

function renderJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function renderInlineJson(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object";
}
