/**
 * Generated by `adapter-core scopes generate`.
 *
 * Scope keys are emitted verbatim from adapter supportedScopes() methods or
 * mapping.yaml `scopes:` keys. They name the per-provider connection filters
 * a persona may set under `integrations.<provider>.scope`.
 */

export const KNOWN_SCOPE_CATALOG = {
  "github": [
    "owner",
    "repo"
  ]
} as const satisfies Record<
  string,
  readonly string[]
>;

export const ADAPTERS_WITHOUT_KNOWN_SCOPES = [
  {
    "packageName": "@relayfile/adapter-airtable",
    "packagePath": "packages/airtable",
    "provider": "airtable",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-asana",
    "packagePath": "packages/asana",
    "provider": "asana",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/azure-blob",
    "packagePath": "packages/azure-blob",
    "provider": "azure-blob",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/box",
    "packagePath": "packages/box",
    "provider": "box",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-calendly",
    "packagePath": "packages/calendly",
    "provider": "calendly",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-clickup",
    "packagePath": "packages/clickup",
    "provider": "clickup",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-confluence",
    "packagePath": "packages/confluence",
    "provider": "confluence",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-docker-hub",
    "packagePath": "packages/docker-hub",
    "provider": "docker-hub",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-dropbox",
    "packagePath": "packages/dropbox",
    "provider": "dropbox",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-fathom",
    "packagePath": "packages/fathom",
    "provider": "fathom",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/gcs",
    "packagePath": "packages/gcs",
    "provider": "gcs",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-gitlab",
    "packagePath": "packages/gitlab",
    "provider": "gitlab",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/gmail",
    "packagePath": "packages/gmail",
    "provider": "gmail",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-google-calendar",
    "packagePath": "packages/google-calendar",
    "provider": "google-calendar",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/google-drive",
    "packagePath": "packages/google-drive",
    "provider": "google-drive",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-granola",
    "packagePath": "packages/granola",
    "provider": "granola",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-hubspot",
    "packagePath": "packages/hubspot",
    "provider": "hubspot",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-intercom",
    "packagePath": "packages/intercom",
    "provider": "intercom",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-jira",
    "packagePath": "packages/jira",
    "provider": "jira",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-linear",
    "packagePath": "packages/linear",
    "provider": "linear",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-mailgun",
    "packagePath": "packages/mailgun",
    "provider": "mailgun",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-mixpanel",
    "packagePath": "packages/mixpanel",
    "provider": "mixpanel",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-notion",
    "packagePath": "packages/notion",
    "provider": "notion",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/onedrive",
    "packagePath": "packages/onedrive",
    "provider": "onedrive",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-pipedrive",
    "packagePath": "packages/pipedrive",
    "provider": "pipedrive",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/postgres",
    "packagePath": "packages/postgres",
    "provider": "postgres",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-reddit",
    "packagePath": "packages/reddit",
    "provider": "reddit",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/redis",
    "packagePath": "packages/redis",
    "provider": "redis",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/s3",
    "packagePath": "packages/s3",
    "provider": "s3",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-salesforce",
    "packagePath": "packages/salesforce",
    "provider": "salesforce",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-segment",
    "packagePath": "packages/segment",
    "provider": "segment",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-sendgrid",
    "packagePath": "packages/sendgrid",
    "provider": "sendgrid",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/sharepoint",
    "packagePath": "packages/sharepoint",
    "provider": "sharepoint",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-shopify",
    "packagePath": "packages/shopify",
    "provider": "shopify",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-slack",
    "packagePath": "packages/slack",
    "provider": "slack",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-stripe",
    "packagePath": "packages/stripe",
    "provider": "stripe",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-teams",
    "packagePath": "packages/teams",
    "provider": "teams",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-x",
    "packagePath": "packages/x",
    "provider": "x",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  },
  {
    "packageName": "@relayfile/adapter-zendesk",
    "packagePath": "packages/zendesk",
    "provider": "zendesk",
    "reason": "No supportedScopes() implementation and no mapping.yaml scopes block"
  }
] as const;

export type KnownScopeProviderName = keyof typeof KNOWN_SCOPE_CATALOG;
export type KnownScopeKey<P extends KnownScopeProviderName> =
  (typeof KNOWN_SCOPE_CATALOG)[P][number];
