import { createHash } from "node:crypto";
import {
  access,
  mkdir,
  readdir,
  readFile,
  writeFile,
} from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { pathToFileURL } from "node:url";

import {
  INBOUND_CAPABILITY_CATALOG_SCHEMA,
  INBOUND_CAPABILITY_SCHEMA,
  type InboundCapabilityDeclaration,
  type InboundLogicalKeyPolicy,
  type InboundSource,
} from "./types.js";
import { findRepoRoot } from "../triggers/catalog-generator.js";

export interface InboundCapabilityCatalogSource {
  readonly packageName: string;
  readonly packagePath: string;
  readonly providerId: string;
  readonly capabilityIds: readonly string[];
}

export interface InboundCapabilityCatalogGeneration {
  readonly catalog: readonly InboundCapabilityDeclaration[];
  readonly catalogVersion: `sha256:${string}`;
  readonly sources: readonly InboundCapabilityCatalogSource[];
}

export interface WriteInboundCapabilityCatalogOptions {
  readonly check?: boolean;
  readonly repoRoot?: string;
}

interface AdapterPackage {
  readonly dir: string;
  readonly packageName: string;
  readonly relativePath: string;
}

const GENERATED_HEADER = `/**
 * Generated by \`adapter-core inbound generate\`.
 *
 * Source declarations live in each adapter's \`src/inbound.ts\`. Do not edit.
 */
`;

const NON_ADAPTER_PACKAGES = new Set([
  "@relayfile/adapter-core",
  "@relayfile/webhook-server",
  "@relayfile/relay-helpers",
]);

export async function generateInboundCapabilityCatalog(
  repoRoot?: string,
): Promise<InboundCapabilityCatalogGeneration> {
  const root = repoRoot ? resolve(repoRoot) : await findRepoRoot();
  const packages = await listDeclaringAdapterPackages(root);
  const catalog: InboundCapabilityDeclaration[] = [];
  const sources: InboundCapabilityCatalogSource[] = [];

  for (const adapterPackage of packages) {
    const declarations = await readInboundCapabilities(adapterPackage);
    if (declarations.length === 0) {
      throw new Error(
        `${adapterPackage.relativePath}/src/inbound.ts exports no inboundCapabilities`,
      );
    }
    validateInboundCapabilityCatalog(declarations);
    const providerId = validateAdapterPackageInboundCapabilities(
      adapterPackage.relativePath,
      declarations,
    );
    catalog.push(...declarations);
    sources.push({
      packageName: adapterPackage.packageName,
      packagePath: adapterPackage.relativePath,
      providerId,
      capabilityIds: declarations.map(({ id }) => id).sort(),
    });
  }

  catalog.sort((left, right) => left.id.localeCompare(right.id));
  validateInboundCapabilityCatalog(catalog);
  const catalogVersion = catalogDigest(catalog);
  return {
    catalog,
    catalogVersion,
    sources: sources.sort(
      (left, right) =>
        left.packagePath.localeCompare(right.packagePath) ||
        left.providerId.localeCompare(right.providerId),
    ),
  };
}

export async function writeInboundCapabilityCatalog(
  options: WriteInboundCapabilityCatalogOptions = {},
): Promise<InboundCapabilityCatalogGeneration> {
  const repoRoot = options.repoRoot
    ? resolve(options.repoRoot)
    : await findRepoRoot();
  const generation = await generateInboundCapabilityCatalog(repoRoot);
  const paths = inboundCapabilityCatalogPaths(repoRoot);
  const expectedFiles = new Map([
    [paths.catalogJson, renderInboundCapabilityCatalogJson(generation)],
    [paths.catalogTs, renderInboundCapabilityCatalogModule(generation)],
  ]);

  if (options.check) {
    const mismatches: string[] = [];
    for (const [filePath, expected] of expectedFiles) {
      let actual = "";
      try {
        actual = await readFile(filePath, "utf8");
      } catch {
        mismatches.push(relative(repoRoot, filePath));
        continue;
      }
      if (actual !== expected) mismatches.push(relative(repoRoot, filePath));
    }
    if (mismatches.length > 0) {
      throw new Error(
        [
          "Inbound capability catalog is out of sync.",
          "Build adapters, then run:",
          "",
          "  npx adapter-core inbound generate",
          "",
          `Stale files: ${mismatches.join(", ")}`,
        ].join("\n"),
      );
    }
    return generation;
  }

  for (const [filePath, contents] of expectedFiles) {
    await mkdir(dirname(filePath), { recursive: true });
    await writeFile(filePath, contents);
  }
  return generation;
}

export function inboundCapabilityCatalogPaths(repoRoot: string): {
  catalogJson: string;
  catalogTs: string;
} {
  const directory = join(repoRoot, "packages", "core", "src", "inbound");
  return {
    catalogJson: join(directory, "catalog.generated.json"),
    catalogTs: join(directory, "catalog.generated.ts"),
  };
}

export function renderInboundCapabilityCatalogModule(
  generation: InboundCapabilityCatalogGeneration,
): string {
  return `${GENERATED_HEADER}
import type { InboundCapabilityDeclaration } from "./types.js";

export const INBOUND_CAPABILITY_CATALOG: readonly InboundCapabilityDeclaration[] = ${JSON.stringify(
    generation.catalog,
    null,
    2,
  )} as const;
export const INBOUND_CAPABILITY_CATALOG_VERSION = ${JSON.stringify(
    generation.catalogVersion,
  )} as const;
`;
}

function renderInboundCapabilityCatalogJson(
  generation: InboundCapabilityCatalogGeneration,
): string {
  return `${JSON.stringify(
    {
      schema: INBOUND_CAPABILITY_CATALOG_SCHEMA,
      catalogVersion: generation.catalogVersion,
      capabilities: generation.catalog,
    },
    null,
    2,
  )}\n`;
}

async function listDeclaringAdapterPackages(
  repoRoot: string,
): Promise<AdapterPackage[]> {
  const packagesDir = join(repoRoot, "packages");
  const entries = await readdir(packagesDir, { withFileTypes: true });
  const packages: AdapterPackage[] = [];

  for (const entry of entries.sort((left, right) =>
    left.name.localeCompare(right.name),
  )) {
    if (!entry.isDirectory()) continue;
    const dir = join(packagesDir, entry.name);
    let packageJson: { name?: string };
    try {
      packageJson = JSON.parse(
        await readFile(join(dir, "package.json"), "utf8"),
      ) as { name?: string };
    } catch {
      continue;
    }
    if (
      !packageJson.name?.startsWith("@relayfile/") ||
      NON_ADAPTER_PACKAGES.has(packageJson.name)
    ) {
      continue;
    }
    try {
      await access(join(dir, "src", "inbound.ts"));
    } catch {
      continue;
    }
    packages.push({
      dir,
      packageName: packageJson.name,
      relativePath: relative(repoRoot, dir),
    });
  }
  return packages;
}

async function readInboundCapabilities(
  adapterPackage: AdapterPackage,
): Promise<InboundCapabilityDeclaration[]> {
  const entryPoint = await firstExistingPath([
    join(adapterPackage.dir, "dist", "inbound.js"),
    join(adapterPackage.dir, "dist", "src", "inbound.js"),
  ]);
  if (!entryPoint) {
    throw new Error(
      `Build ${adapterPackage.packageName} before generating the inbound catalog; dist/inbound.js is missing`,
    );
  }

  let moduleExports: Record<string, unknown>;
  try {
    moduleExports = (await import(
      `${pathToFileURL(entryPoint).href}?catalog=${Date.now()}`
    )) as Record<string, unknown>;
  } catch (error) {
    throw new Error(
      `Could not import ${adapterPackage.packageName} inbound declarations: ${errorMessage(error)}`,
      { cause: error },
    );
  }
  return normalizeCapabilities(moduleExports.inboundCapabilities);
}

function normalizeCapabilities(value: unknown): InboundCapabilityDeclaration[] {
  if (!Array.isArray(value)) return [];
  return value.map((item, index) => normalizeCapability(item, index));
}

function normalizeCapability(
  value: unknown,
  index: number,
): InboundCapabilityDeclaration {
  const record = requireRecord(value, `inboundCapabilities[${index}]`);
  const source = requireEnum(
    record.source,
    ["nango", "hookdeck"] as const,
    "source",
  );
  const logicalKeyRecord = requireRecord(record.logicalKey, "logicalKey");
  const logicalKey: InboundLogicalKeyPolicy = {
    version: requireLiteral(logicalKeyRecord.version, "1", "logicalKey.version"),
    strategies: requireStringArray(
      logicalKeyRecord.strategies,
      "logicalKey.strategies",
    ).map((strategy) =>
      requireEnum(
        strategy,
        [
          "provider-delivery-id",
          "nango-sync-page",
          "hookdeck-delivery-id",
          "semantic-payload",
        ] as const,
        "logicalKey.strategies",
      ),
    ),
    ...(logicalKeyRecord.providerDeliveryIdHeaders === undefined
      ? {}
      : {
          providerDeliveryIdHeaders: requireStringArray(
            logicalKeyRecord.providerDeliveryIdHeaders,
            "logicalKey.providerDeliveryIdHeaders",
          ).map(normalizeHeader),
        }),
    ...(logicalKeyRecord.hookdeckDeliveryIdHeaders === undefined
      ? {}
      : {
          hookdeckDeliveryIdHeaders: requireStringArray(
            logicalKeyRecord.hookdeckDeliveryIdHeaders,
            "logicalKey.hookdeckDeliveryIdHeaders",
          ).map(normalizeHeader),
        }),
    unknownEventFallback: requireLiteral(
      logicalKeyRecord.unknownEventFallback,
      "raw-body",
      "logicalKey.unknownEventFallback",
    ),
    semanticPayload: requireLiteral(
      logicalKeyRecord.semanticPayload,
      "canonical-json-v1",
      "logicalKey.semanticPayload",
    ),
  };

  const detection =
    record.detection === undefined
      ? undefined
      : requireRecord(record.detection, "detection");
  const pathRoot = requireString(record.pathRoot, "pathRoot");
  if (!pathRoot.startsWith("/")) {
    throw new Error(`pathRoot must start with "/": ${pathRoot}`);
  }

  return {
    schema: requireLiteral(
      record.schema,
      INBOUND_CAPABILITY_SCHEMA,
      "schema",
    ),
    id: requireString(record.id, "id"),
    providerId: requireString(record.providerId, "providerId"),
    pathRoot: pathRoot as `/${string}`,
    providerConfigAliases: requireStringArray(
      record.providerConfigAliases,
      "providerConfigAliases",
    )
      .map(normalizeToken)
      .sort(),
    source,
    eventKinds: requireStringArray(record.eventKinds, "eventKinds").sort(),
    ...(detection
      ? {
          detection: {
            headerAny: requireStringArray(
              detection.headerAny,
              "detection.headerAny",
            )
              .map(normalizeHeader)
              .sort(),
          },
        }
      : {}),
    logicalKey,
  };
}

export function validateInboundCapabilityCatalog(
  catalog: readonly InboundCapabilityDeclaration[],
): void {
  const ids = new Set<string>();
  const aliases = new Map<string, string>();
  const detectionHeaders = new Map<string, string>();
  const providerPathRoots = new Map<string, string>();
  const pathRootProviders = new Map<string, string>();
  for (const capability of catalog) {
    if (ids.has(capability.id)) {
      throw new Error(`Duplicate inbound capability id: ${capability.id}`);
    }
    ids.add(capability.id);
    const priorPathRoot = providerPathRoots.get(capability.providerId);
    if (priorPathRoot && priorPathRoot !== capability.pathRoot) {
      throw new Error(
        `${capability.providerId} declares conflicting path roots: ${priorPathRoot} and ${capability.pathRoot}`,
      );
    }
    providerPathRoots.set(capability.providerId, capability.pathRoot);

    const priorProviderId = pathRootProviders.get(capability.pathRoot);
    if (priorProviderId && priorProviderId !== capability.providerId) {
      throw new Error(
        `path root ${capability.pathRoot} is claimed by both ${priorProviderId} and ${capability.providerId}`,
      );
    }
    pathRootProviders.set(capability.pathRoot, capability.providerId);

    if (!capability.eventKinds.length) {
      throw new Error(`${capability.id} must declare at least one event kind`);
    }
    if (
      !capability.logicalKey.strategies.includes("semantic-payload") ||
      capability.logicalKey.strategies.includes("raw-body" as never)
    ) {
      throw new Error(
        `${capability.id} must use semantic-payload for known events and reserve raw-body for unknown events`,
      );
    }
    if (capability.source === "hookdeck" && !capability.detection?.headerAny?.length) {
      throw new Error(`${capability.id} Hookdeck capability needs detection.headerAny`);
    }
    for (const alias of capability.providerConfigAliases) {
      const key = `${capability.source}:${normalizeToken(alias)}`;
      const prior = aliases.get(key);
      if (prior && prior !== capability.id) {
        throw new Error(
          `Inbound alias ${alias} maps to both ${prior} and ${capability.id}`,
        );
      }
      aliases.set(key, capability.id);
    }
    for (const header of capability.detection?.headerAny ?? []) {
      const key = normalizeHeader(header);
      const prior = detectionHeaders.get(key);
      if (prior && prior !== capability.id) {
        throw new Error(
          `Inbound detection header ${header} maps to both ${prior} and ${capability.id}`,
        );
      }
      detectionHeaders.set(key, capability.id);
    }
  }
}

export function validateAdapterPackageInboundCapabilities(
  packagePath: string,
  declarations: readonly InboundCapabilityDeclaration[],
): string {
  const providerIds = [
    ...new Set(declarations.map((declaration) => declaration.providerId)),
  ];
  if (providerIds.length !== 1) {
    throw new Error(
      `${packagePath}/src/inbound.ts must declare exactly one provider id; found ${providerIds.join(", ")}`,
    );
  }
  return providerIds[0]!;
}

function catalogDigest(
  catalog: readonly InboundCapabilityDeclaration[],
): `sha256:${string}` {
  return `sha256:${createHash("sha256")
    .update(JSON.stringify(catalog))
    .digest("hex")}`;
}

async function firstExistingPath(
  paths: readonly string[],
): Promise<string | undefined> {
  for (const path of paths) {
    try {
      await access(path);
      return path;
    } catch {
      // Try next output layout.
    }
  }
  return undefined;
}

function requireRecord(value: unknown, field: string): Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(`${field} must be an object`);
  }
  return value as Record<string, unknown>;
}

function requireString(value: unknown, field: string): string {
  if (typeof value !== "string" || !value.trim()) {
    throw new Error(`${field} must be a non-empty string`);
  }
  return value.trim();
}

function requireStringArray(value: unknown, field: string): string[] {
  if (!Array.isArray(value) || value.length === 0) {
    throw new Error(`${field} must be a non-empty string array`);
  }
  return [...new Set(value.map((item) => requireString(item, field)))];
}

function requireLiteral<const T extends string>(
  value: unknown,
  expected: T,
  field: string,
): T {
  if (value !== expected) {
    throw new Error(`${field} must equal ${expected}`);
  }
  return expected;
}

function requireEnum<const T extends readonly string[]>(
  value: unknown,
  allowed: T,
  field: string,
): T[number] {
  if (typeof value !== "string" || !allowed.includes(value)) {
    throw new Error(`${field} must be one of ${allowed.join(", ")}`);
  }
  return value as T[number];
}

function normalizeToken(value: string): string {
  return value.trim().toLowerCase();
}

function normalizeHeader(value: string): string {
  return normalizeToken(value);
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
