import { access, mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import YAML from "yaml";

export type TriggerCatalog = Record<string, string[]>;

export interface AdapterWithoutKnownTriggers {
  packageName: string;
  packagePath: string;
  provider: string;
  reason: string;
}

export interface TriggerCatalogSource {
  packageName: string;
  packagePath: string;
  provider: string;
  source: "mapping.webhooks" | "supportedEvents";
}

export interface TriggerCatalogGeneration {
  catalog: TriggerCatalog;
  sources: TriggerCatalogSource[];
  adaptersWithoutKnownTriggers: AdapterWithoutKnownTriggers[];
}

export interface WriteTriggerCatalogOptions {
  check?: boolean;
  repoRoot?: string;
}

interface AdapterPackage {
  dir: string;
  packageName: string;
  provider: string;
  relativePath: string;
}

const GENERATED_HEADER = `/**
 * Generated by \`adapter-core triggers generate\`.
 *
 * Event names are emitted verbatim from adapter supportedEvents() methods or
 * mapping.yaml webhooks keys. Do not normalize names across providers: the
 * cloud runtime matches persona triggers against each adapter's real event.type.
 */
`;

const NON_ADAPTER_PACKAGES = new Set([
  "@relayfile/adapter-core",
  "@relayfile/webhook-server",
  "@relayfile/relay-helpers"
]);

export async function generateTriggerCatalog(repoRoot?: string): Promise<TriggerCatalogGeneration> {
  repoRoot = repoRoot ? resolve(repoRoot) : await findRepoRoot();
  const packages = await listAdapterPackages(repoRoot);
  const entries: Array<{ provider: string; events: string[] }> = [];
  const sources: TriggerCatalogSource[] = [];
  const adaptersWithoutKnownTriggers: AdapterWithoutKnownTriggers[] = [];

  for (const adapterPackage of packages) {
    const mappingEvents = await readMappingWebhookEvents(repoRoot, adapterPackage);
    const supportedEvents = await readSupportedEvents(adapterPackage);
    let hasKnownTriggers = false;

    if (supportedEvents.events.length > 0) {
      entries.push({
        provider: supportedEvents.provider,
        events: supportedEvents.events,
      });
      sources.push({
        packageName: adapterPackage.packageName,
        packagePath: adapterPackage.relativePath,
        provider: supportedEvents.provider,
        source: "supportedEvents",
      });
      hasKnownTriggers = true;
    }

    if (mappingEvents.events.length > 0 && mappingEvents.source === "core.mapping.webhooks") {
      // Storage-bridge adapters can keep runtime-only webhook names in
      // mapping.yaml. Merge those keys with supportedEvents() rather than
      // replacing either source; personas may use names from both contracts.
      const provider = supportedEvents.events.length > 0 ? supportedEvents.provider : adapterPackage.provider;
      entries.push({
        provider,
        events: mappingEvents.events,
      });
      sources.push({
        packageName: adapterPackage.packageName,
        packagePath: adapterPackage.relativePath,
        provider,
        source: "mapping.webhooks",
      });
      hasKnownTriggers = true;
    }

    if (hasKnownTriggers) {
      continue;
    }

    if (mappingEvents.events.length > 0) {
      entries.push({
        provider: adapterPackage.provider,
        events: mappingEvents.events,
      });
      sources.push({
        packageName: adapterPackage.packageName,
        packagePath: adapterPackage.relativePath,
        provider: adapterPackage.provider,
        source: "mapping.webhooks",
      });
      continue;
    }

    adaptersWithoutKnownTriggers.push({
      packageName: adapterPackage.packageName,
      packagePath: adapterPackage.relativePath,
      provider: adapterPackage.provider,
      reason:
        supportedEvents.error ??
        "No supportedEvents() implementation and no mapping.yaml webhooks block",
    });
  }

  return {
    catalog: sortCatalog(entries),
    sources: sources.sort(compareByPackagePath),
    adaptersWithoutKnownTriggers: adaptersWithoutKnownTriggers.sort(compareByPackagePath),
  };
}

export async function writeTriggerCatalog(
  options: WriteTriggerCatalogOptions = {}
): Promise<TriggerCatalogGeneration> {
  const repoRoot = options.repoRoot ? resolve(options.repoRoot) : await findRepoRoot();
  const generation = await generateTriggerCatalog(repoRoot);
  const paths = triggerCatalogPaths(repoRoot);
  const expectedFiles = new Map([
    [paths.catalogJson, renderJson(generation.catalog)],
    [paths.noEventJson, renderJson(generation.adaptersWithoutKnownTriggers)],
    [paths.catalogTs, renderTriggerCatalogModule(generation)],
  ]);

  if (options.check) {
    const mismatches: string[] = [];
    for (const [filePath, expected] of expectedFiles) {
      let actual = "";
      try {
        actual = await readFile(filePath, "utf8");
      } catch {
        mismatches.push(relative(repoRoot, filePath));
        continue;
      }
      if (actual !== expected) {
        mismatches.push(relative(repoRoot, filePath));
      }
    }
    if (mismatches.length > 0) {
      throw new Error(
        `Trigger catalog is out of sync. Run \`adapter-core triggers generate\`. Stale files: ${mismatches.join(
          ", "
        )}`
      );
    }
    return generation;
  }

  for (const [filePath, contents] of expectedFiles) {
    await mkdir(dirname(filePath), { recursive: true });
    await writeFile(filePath, contents);
  }

  return generation;
}

export function triggerCatalogPaths(repoRoot: string): {
  catalogJson: string;
  noEventJson: string;
  catalogTs: string;
} {
  const triggerDir = join(repoRoot, "packages", "core", "src", "triggers");
  return {
    catalogJson: join(triggerDir, "catalog.generated.json"),
    noEventJson: join(triggerDir, "adapters-without-known-triggers.generated.json"),
    catalogTs: join(triggerDir, "catalog.generated.ts"),
  };
}

export function renderTriggerCatalogModule(generation: TriggerCatalogGeneration): string {
  return `${GENERATED_HEADER}
export const KNOWN_TRIGGER_CATALOG = ${renderInlineJson(generation.catalog)} as const satisfies Record<
  string,
  readonly string[]
>;

export const ADAPTERS_WITHOUT_KNOWN_TRIGGERS = ${renderInlineJson(generation.adaptersWithoutKnownTriggers)} as const;

export type KnownProviderName = keyof typeof KNOWN_TRIGGER_CATALOG;
export type KnownTriggerName<P extends KnownProviderName> =
  (typeof KNOWN_TRIGGER_CATALOG)[P][number];
`;
}

export async function findRepoRoot(start = process.cwd()): Promise<string> {
  let current = resolve(start);

  while (true) {
    const packagePath = join(current, "package.json");
    try {
      const pkg = JSON.parse(await readFile(packagePath, "utf8")) as { name?: string };
      if (pkg.name === "relayfile-adapters") {
        return current;
      }
    } catch {
      // Keep walking.
    }

    const parent = dirname(current);
    if (parent === current) {
      throw new Error(`Could not find relayfile-adapters repo root from ${start}`);
    }
    current = parent;
  }
}

async function listAdapterPackages(repoRoot: string): Promise<AdapterPackage[]> {
  const packagesDir = join(repoRoot, "packages");
  const names = await readdir(packagesDir);
  const packages: AdapterPackage[] = [];

  for (const name of names.sort()) {
    const dir = join(packagesDir, name);
    const packageJsonPath = join(dir, "package.json");
    let packageJson: { name?: string };
    try {
      packageJson = JSON.parse(await readFile(packageJsonPath, "utf8")) as { name?: string };
    } catch {
      continue;
    }
    // Only @relayfile/* packages are adapters. Skip other scopes (e.g.
    // @agentworkforce/persona-* data packages) so they are not scanned as
    // adapters and listed in the adapters-without-known-* catalogs.
    if (
      !packageJson.name ||
      !packageJson.name.startsWith("@relayfile/") ||
      NON_ADAPTER_PACKAGES.has(packageJson.name)
    ) {
      continue;
    }
    packages.push({
      dir,
      packageName: packageJson.name,
      provider: inferProviderSlug(packageJson.name, name),
      relativePath: relative(repoRoot, dir),
    });
  }

  return packages;
}

async function readSupportedEvents(
  adapterPackage: AdapterPackage
): Promise<{ events: string[]; provider: string; error?: string }> {
  const entryPoint = await firstExistingPath([
    join(adapterPackage.dir, "dist", "index.js"),
    join(adapterPackage.dir, "dist", "src", "index.js"),
    join(adapterPackage.dir, "src", "index.ts"),
  ]);
  if (!entryPoint) {
    return {
      events: [],
      provider: adapterPackage.provider,
      error: "No adapter entrypoint at dist/index.js, dist/src/index.js, or src/index.ts",
    };
  }

  let moduleExports: Record<string, unknown>;
  try {
    moduleExports = (await import(pathToFileURL(entryPoint).href)) as Record<string, unknown>;
  } catch (error) {
    return {
      events: [],
      provider: adapterPackage.provider,
      error: `Could not import built adapter entrypoint: ${errorMessage(error)}`,
    };
  }

  const candidates = Object.entries(moduleExports)
    .filter(([, value]) => hasSupportedEventsPrototype(value))
    .sort(([left], [right]) => left.localeCompare(right)) as Array<
    [string, new (...args: never[]) => { name?: unknown; supportedEvents(): string[] }]
  >;

  for (const [, Candidate] of candidates) {
    const instance = instantiateAdapter(Candidate);
    if (!instance) {
      continue;
    }
    let events: unknown;
    try {
      events = instance.supportedEvents();
    } catch {
      continue;
    }
    const normalized = normalizeEvents(events);
    if (normalized.length > 0) {
      return {
        events: normalized,
        provider: typeof instance.name === "string" && instance.name ? instance.name : adapterPackage.provider,
      };
    }
  }

  return { events: [], provider: adapterPackage.provider };
}

async function firstExistingPath(paths: string[]): Promise<string | undefined> {
  for (const path of paths) {
    try {
      await access(path);
      return path;
    } catch {
      // Try the next path.
    }
  }
  return undefined;
}

type MappingWebhookEvents = {
  events: string[];
  source?: "package.mapping.webhooks" | "core.mapping.webhooks";
};

async function readMappingWebhookEvents(
  repoRoot: string,
  adapterPackage: AdapterPackage
): Promise<MappingWebhookEvents> {
  const packageEvents = await readMappingWebhookEventsFromDir(adapterPackage.dir);
  if (packageEvents.length > 0) {
    return { events: packageEvents, source: "package.mapping.webhooks" };
  }

  const coreMappingDir = join(repoRoot, "packages", "core", "mappings");
  const coreEvents = await readMappingWebhookEventsFromFiles([
    join(coreMappingDir, `${adapterPackage.provider}.mapping.yaml`),
  ]);
  return {
    events: coreEvents,
    ...(coreEvents.length > 0 ? { source: "core.mapping.webhooks" as const } : {}),
  };
}

async function readMappingWebhookEventsFromDir(packageDir: string): Promise<string[]> {
  const filenames = (await readdir(packageDir)).filter((name) => name.endsWith(".mapping.yaml")).sort();
  return readMappingWebhookEventsFromFiles(filenames.map((filename) => join(packageDir, filename)));
}

async function readMappingWebhookEventsFromFiles(paths: string[]): Promise<string[]> {
  const events = new Set<string>();

  for (const path of paths) {
    let contents: string;
    try {
      contents = await readFile(path, "utf8");
    } catch {
      continue;
    }
    const parsed = YAML.parse(contents) as { webhooks?: unknown } | null;
    if (!parsed || !isRecord(parsed.webhooks)) {
      continue;
    }
    for (const eventName of Object.keys(parsed.webhooks)) {
      events.add(eventName);
    }
  }

  return [...events].sort();
}

function instantiateAdapter(
  Candidate: new (...args: never[]) => { name?: unknown; supportedEvents(): string[] }
): { name?: unknown; supportedEvents(): string[] } | undefined {
  const client = createClientStub();
  const provider = createProviderStub();
  const attempts: unknown[][] = [
    [client, provider, {}],
    [provider, {}],
    [client, {}],
    [client, provider],
    [provider],
    [client],
    [{}],
    [],
  ];

  for (const args of attempts) {
    try {
      return new Candidate(...(args as never[]));
    } catch {
      // Try the next common adapter constructor shape.
    }
  }

  return undefined;
}

function createClientStub(): Record<string, unknown> {
  return {
    async deleteFile() {
      return undefined;
    },
    getWrittenRevision() {
      return undefined;
    },
    async readFile() {
      return undefined;
    },
    async writeFile() {
      return {};
    },
  };
}

function createProviderStub(): Record<string, unknown> {
  return {
    name: "catalog-generator",
    async proxy() {
      return { status: 200, headers: {}, body: null };
    },
    async healthCheck() {
      return { ok: true };
    },
  };
}

function hasSupportedEventsPrototype(
  value: unknown
): value is new (...args: never[]) => { name?: unknown; supportedEvents(): string[] } {
  return (
    typeof value === "function" &&
    isRecord(value.prototype) &&
    typeof value.prototype.supportedEvents === "function"
  );
}

function normalizeEvents(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }
  return [...new Set(value.filter((event): event is string => typeof event === "string" && event.length > 0))].sort();
}

function sortCatalog(entries: Array<{ provider: string; events: string[] }>): TriggerCatalog {
  const catalog = new Map<string, Set<string>>();

  for (const entry of entries) {
    const existing = catalog.get(entry.provider) ?? new Set<string>();
    for (const event of entry.events) {
      existing.add(event);
    }
    catalog.set(entry.provider, existing);
  }

  return Object.fromEntries(
    [...catalog.entries()]
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([provider, events]) => [provider, [...events].sort()])
  );
}

function inferProviderSlug(packageName: string, directoryName: string): string {
  if (packageName.startsWith("@relayfile/adapter-")) {
    return packageName.slice("@relayfile/adapter-".length);
  }
  if (packageName.startsWith("@relayfile/")) {
    return packageName.slice("@relayfile/".length);
  }
  return directoryName;
}

function compareByPackagePath(
  left: { packagePath: string; provider: string },
  right: { packagePath: string; provider: string }
): number {
  return left.packagePath.localeCompare(right.packagePath) || left.provider.localeCompare(right.provider);
}

function renderJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function renderInlineJson(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object";
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
