#!/usr/bin/env node
// Assemble the persona spec from its two human-editable sources of truth:
//   - persona.base.json : the persona metadata (everything except the manual)
//   - AGENTS.md         : the operations manual (becomes `agentsMdContent`)
//
// Emits src/persona.generated.ts (a committed, typed `as const` literal) so the
// package builds with plain `tsc` and consumers get a fully-assembled spec
// object with `agentsMdContent` inlined.
//
// Run `node scripts/assemble.mjs` to regenerate, or `--check` to fail on drift
// (used by `npm test` / CI).

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const basePath = join(pkgRoot, 'persona.base.json');
const agentsPath = join(pkgRoot, 'AGENTS.md');
const outPath = join(pkgRoot, 'src', 'persona.generated.ts');

const base = JSON.parse(readFileSync(basePath, 'utf8'));
const agentsMdContent = readFileSync(agentsPath, 'utf8');

// Reconstruct in the original on-disk key order: agentsMdContent sits directly
// after mcpServers. Iterating base keys keeps this resilient to added fields.
const assembled = {};
for (const [key, value] of Object.entries(base)) {
  assembled[key] = value;
  if (key === 'mcpServers') {
    assembled.agentsMdContent = agentsMdContent;
  }
}
if (!('agentsMdContent' in assembled)) {
  // mcpServers absent — append at the end so we never silently drop the manual.
  assembled.agentsMdContent = agentsMdContent;
}

const banner =
  '// AUTO-GENERATED by scripts/assemble.mjs — do not edit by hand.\n' +
  '// Sources of truth: persona.base.json + AGENTS.md\n' +
  '// Regenerate with: npm run build  (or: node scripts/assemble.mjs)\n\n';

const contents =
  banner + `const persona = ${JSON.stringify(assembled, null, 2)} as const;\n\nexport default persona;\n`;

const checkOnly = process.argv.includes('--check');

if (checkOnly) {
  let current = '';
  try {
    current = readFileSync(outPath, 'utf8');
  } catch {
    current = '';
  }
  if (current !== contents) {
    console.error(
      'persona.generated.ts is out of date with persona.base.json / AGENTS.md.\n' +
        'Run `npm run build` (or `node scripts/assemble.mjs`) and commit the result.',
    );
    process.exit(1);
  }
  console.log('persona.generated.ts is in sync.');
  process.exit(0);
}

writeFileSync(outPath, contents);
console.log(`Wrote ${outPath} (${agentsMdContent.length} bytes of manual).`);
