import { access, mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import YAML from "yaml";

import { findRepoRoot } from "../triggers/catalog-generator.js";

/**
 * Per-provider connection **scope** keys — the user-facing filter params a
 * persona may set under `integrations.<provider>.scope` (e.g. github →
 * `owner`/`repo`). Distinct from infra config (tokens, connectionId) and from
 * trigger event names. The cloud adapter decides what each key means; this
 * catalog just enumerates the declared keys per provider so persona authoring
 * can autocomplete + lint them.
 */
export type ScopeKeyCatalog = Record<string, string[]>;

export interface AdapterWithoutKnownScopeKeys {
  packageName: string;
  packagePath: string;
  provider: string;
  reason: string;
}

export interface ScopeKeyCatalogSource {
  packageName: string;
  packagePath: string;
  provider: string;
  source: "mapping.scopeKeys" | "supportedScopeKeys";
}

export interface ScopeKeyCatalogGeneration {
  catalog: ScopeKeyCatalog;
  sources: ScopeKeyCatalogSource[];
  adaptersWithoutKnownScopeKeys: AdapterWithoutKnownScopeKeys[];
}

export interface WriteScopeKeyCatalogOptions {
  check?: boolean;
  repoRoot?: string;
}

interface AdapterPackage {
  dir: string;
  packageName: string;
  provider: string;
  relativePath: string;
}

const GENERATED_HEADER = `/**
 * Generated by \`adapter-core scope-keys generate\`.
 *
 * Scope keys are emitted verbatim from adapter supportedScopeKeys() methods or
 * mapping.yaml \`scopeKeys:\` keys. They name the per-provider connection filters
 * a persona may set under \`integrations.<provider>.scope\`.
 */
`;

const NON_ADAPTER_PACKAGES = new Set([
  "@relayfile/adapter-core",
  "@relayfile/webhook-server",
  "@relayfile/relay-helpers"
]);

export async function generateScopeKeyCatalog(repoRoot?: string): Promise<ScopeKeyCatalogGeneration> {
  repoRoot = repoRoot ? resolve(repoRoot) : await findRepoRoot();
  const packages = await listAdapterPackages(repoRoot);
  const entries: Array<{ provider: string; keys: string[] }> = [];
  const sources: ScopeKeyCatalogSource[] = [];
  const adaptersWithoutKnownScopeKeys: AdapterWithoutKnownScopeKeys[] = [];

  for (const adapterPackage of packages) {
    const mappingScopeKeys = await readMappingScopeKeys(repoRoot, adapterPackage);
    const supportedScopeKeys = await readSupportedScopeKeys(adapterPackage);
    let hasKnownScopeKeys = false;

    if (supportedScopeKeys.keys.length > 0) {
      // `supportedScopeKeys()` is authoritative. Unlike triggers (where mapping
      // webhooks are a legitimate second delivery contract), scope keys have
      // one source of truth, so the mapping block is a FALLBACK only — never
      // merged. Merging would let a stale `scopeKeys:` YAML entry outlive an
      // adapter that renamed/removed a scope, and persona tooling would then
      // autocomplete/lint a key the adapter no longer supports.
      entries.push({ provider: supportedScopeKeys.provider, keys: supportedScopeKeys.keys });
      sources.push({
        packageName: adapterPackage.packageName,
        packagePath: adapterPackage.relativePath,
        provider: supportedScopeKeys.provider,
        source: "supportedScopeKeys",
      });
      hasKnownScopeKeys = true;
    } else if (mappingScopeKeys.length > 0) {
      entries.push({ provider: adapterPackage.provider, keys: mappingScopeKeys });
      sources.push({
        packageName: adapterPackage.packageName,
        packagePath: adapterPackage.relativePath,
        provider: adapterPackage.provider,
        source: "mapping.scopeKeys",
      });
      hasKnownScopeKeys = true;
    }

    if (hasKnownScopeKeys) {
      continue;
    }

    adaptersWithoutKnownScopeKeys.push({
      packageName: adapterPackage.packageName,
      packagePath: adapterPackage.relativePath,
      provider: adapterPackage.provider,
      reason:
        supportedScopeKeys.error ??
        "No supportedScopeKeys() implementation and no mapping.yaml scopeKeys block",
    });
  }

  return {
    catalog: sortCatalog(entries),
    sources: sources.sort(compareByPackagePath),
    adaptersWithoutKnownScopeKeys: adaptersWithoutKnownScopeKeys.sort(compareByPackagePath),
  };
}

export async function writeScopeKeyCatalog(
  options: WriteScopeKeyCatalogOptions = {}
): Promise<ScopeKeyCatalogGeneration> {
  const repoRoot = options.repoRoot ? resolve(options.repoRoot) : await findRepoRoot();
  const generation = await generateScopeKeyCatalog(repoRoot);
  const paths = scopeKeyCatalogPaths(repoRoot);
  const expectedFiles = new Map([
    [paths.catalogJson, renderJson(generation.catalog)],
    [paths.noScopeKeyJson, renderJson(generation.adaptersWithoutKnownScopeKeys)],
    [paths.catalogTs, renderScopeKeyCatalogModule(generation)],
  ]);

  if (options.check) {
    const mismatches: string[] = [];
    for (const [filePath, expected] of expectedFiles) {
      let actual = "";
      try {
        actual = await readFile(filePath, "utf8");
      } catch {
        mismatches.push(relative(repoRoot, filePath));
        continue;
      }
      if (actual !== expected) {
        mismatches.push(relative(repoRoot, filePath));
      }
    }
    if (mismatches.length > 0) {
      throw new Error(
        [
          "Scope-key catalog is out of sync.",
          "To fix, run the following command from the repo root:",
          "",
          "  npx adapter-core scope-keys generate",
          "",
          "  # or, if the package is built locally:",
          "  node packages/core/dist/src/cli.js scope-keys generate",
          "",
          `Stale files: ${mismatches.join(", ")}`,
        ].join("\n")
      );
    }
    return generation;
  }

  for (const [filePath, contents] of expectedFiles) {
    await mkdir(dirname(filePath), { recursive: true });
    await writeFile(filePath, contents);
  }

  return generation;
}

export function scopeKeyCatalogPaths(repoRoot: string): {
  catalogJson: string;
  noScopeKeyJson: string;
  catalogTs: string;
} {
  const scopeDir = join(repoRoot, "packages", "core", "src", "scope-keys");
  return {
    catalogJson: join(scopeDir, "catalog.generated.json"),
    noScopeKeyJson: join(scopeDir, "adapters-without-known-scope-keys.generated.json"),
    catalogTs: join(scopeDir, "catalog.generated.ts"),
  };
}

export function renderScopeKeyCatalogModule(generation: ScopeKeyCatalogGeneration): string {
  return `${GENERATED_HEADER}
export const KNOWN_SCOPE_KEY_CATALOG = ${renderInlineJson(generation.catalog)} as const satisfies Record<
  string,
  readonly string[]
>;

export const ADAPTERS_WITHOUT_KNOWN_SCOPE_KEYS = ${renderInlineJson(generation.adaptersWithoutKnownScopeKeys)} as const;

export type ScopeKeyProvider = keyof typeof KNOWN_SCOPE_KEY_CATALOG;
export type ScopeKey<P extends ScopeKeyProvider> =
  (typeof KNOWN_SCOPE_KEY_CATALOG)[P][number];
`;
}

async function listAdapterPackages(repoRoot: string): Promise<AdapterPackage[]> {
  const packagesDir = join(repoRoot, "packages");
  const names = await readdir(packagesDir);
  const packages: AdapterPackage[] = [];

  for (const name of names.sort()) {
    const dir = join(packagesDir, name);
    const packageJsonPath = join(dir, "package.json");
    let packageJson: { name?: string };
    try {
      packageJson = JSON.parse(await readFile(packageJsonPath, "utf8")) as { name?: string };
    } catch {
      continue;
    }
    // Only @relayfile/* packages are adapters. Skip other scopes (e.g.
    // @agentworkforce/persona-* data packages) so they are not scanned as
    // adapters and listed in the adapters-without-known-* catalogs.
    if (
      !packageJson.name ||
      !packageJson.name.startsWith("@relayfile/") ||
      NON_ADAPTER_PACKAGES.has(packageJson.name)
    ) {
      continue;
    }
    packages.push({
      dir,
      packageName: packageJson.name,
      provider: inferProviderSlug(packageJson.name, name),
      relativePath: relative(repoRoot, dir),
    });
  }

  return packages;
}

async function readSupportedScopeKeys(
  adapterPackage: AdapterPackage
): Promise<{ keys: string[]; provider: string; error?: string }> {
  const sourceEntryPoint = join(adapterPackage.dir, "src", "index.ts");
  const sourceScopes = await readSupportedScopesFromSource(sourceEntryPoint);
  const builtEntryPoint = await firstExistingPath([
    join(adapterPackage.dir, "dist", "index.js"),
    join(adapterPackage.dir, "dist", "src", "index.js"),
  ]);

  let importError: string | undefined;
  if (builtEntryPoint) {
    const supportedScopeKeys = await readSupportedScopeKeysFromModule(adapterPackage, builtEntryPoint);
    if (supportedScopeKeys.keys.length > 0) {
      return supportedScopeKeys;
    }
    // Remember an import failure so it surfaces as the adapter's "no scope
    // keys" reason instead of the generic "no implementation" message — a
    // swallowed import error otherwise hides a real build/runtime problem.
    importError = supportedScopeKeys.error;
  }

  if (sourceScopes.length > 0) {
    return { keys: sourceScopes, provider: adapterPackage.provider };
  }

  if (importError) {
    return { keys: [], provider: adapterPackage.provider, error: importError };
  }

  if (!builtEntryPoint && !(await pathExists(sourceEntryPoint))) {
    return {
      keys: [],
      provider: adapterPackage.provider,
      error: "No adapter entrypoint at dist/index.js, dist/src/index.js, or src/index.ts",
    };
  }

  return { keys: [], provider: adapterPackage.provider };
}

async function readSupportedScopeKeysFromModule(
  adapterPackage: AdapterPackage,
  entryPoint: string
): Promise<{ keys: string[]; provider: string; error?: string }> {
  let moduleExports: Record<string, unknown>;
  try {
    moduleExports = (await import(pathToFileURL(entryPoint).href)) as Record<string, unknown>;
  } catch (error) {
    return {
      keys: [],
      provider: adapterPackage.provider,
      error: `Could not import built adapter entrypoint: ${errorMessage(error)}`,
    };
  }

  const candidates = Object.entries(moduleExports)
    .filter(([, value]) => hasSupportedScopeKeysPrototype(value))
    .sort(([left], [right]) => left.localeCompare(right)) as Array<
    [string, new (...args: never[]) => { name?: unknown; supportedScopeKeys(): string[] }]
  >;

  for (const [, Candidate] of candidates) {
    const instance = instantiateAdapter(Candidate);
    if (!instance) {
      continue;
    }
    let keys: unknown;
    try {
      keys = instance.supportedScopeKeys();
    } catch {
      continue;
    }
    const normalized = normalizeKeys(keys);
    if (normalized.length > 0) {
      return {
        keys: normalized,
        provider: typeof instance.name === "string" && instance.name ? instance.name : adapterPackage.provider,
      };
    }
  }

  return { keys: [], provider: adapterPackage.provider };
}

async function readSupportedScopesFromSource(entryPoint: string): Promise<string[]> {
  const entryPointKeys = await readSupportedScopesFromSourceFile(entryPoint);
  if (entryPointKeys.length > 0) {
    return entryPointKeys;
  }

  return readSupportedScopesFromSourceDir(dirname(entryPoint));
}

async function readSupportedScopesFromSourceFile(filePath: string): Promise<string[]> {
  let contents: string;
  try {
    contents = await readFile(filePath, "utf8");
  } catch {
    return [];
  }

  const supportedScopeKeysMethod =
    /\bsupportedScopeKeys\s*\([^)]*\)\s*(?::[^{]+)?\{\s*return\s*\[([\s\S]*?)\]\s*;?\s*\}/u.exec(contents);
  if (!supportedScopeKeysMethod) {
    return [];
  }

  const keys = new Set<string>();
  const stringLiteral = /["']([^"']+)["']/gu;
  let match: RegExpExecArray | null;
  while ((match = stringLiteral.exec(supportedScopeKeysMethod[1] ?? "")) !== null) {
    keys.add(match[1]);
  }
  return [...keys].sort();
}

async function readSupportedScopesFromSourceDir(dir: string): Promise<string[]> {
  const keys = new Set<string>();
  for (const filePath of await sourceFiles(dir)) {
    for (const key of await readSupportedScopesFromSourceFile(filePath)) {
      keys.add(key);
    }
  }
  return [...keys].sort();
}

async function sourceFiles(dir: string): Promise<string[]> {
  let entries: import("node:fs").Dirent[];
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return [];
  }

  const files: string[] = [];
  for (const entry of entries) {
    const filePath = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "dist" || entry.name === "node_modules") continue;
      files.push(...(await sourceFiles(filePath)));
    } else if (entry.isFile() && filePath.endsWith(".ts") && !filePath.endsWith(".d.ts")) {
      files.push(filePath);
    }
  }
  return files.sort();
}

async function readMappingScopeKeys(repoRoot: string, adapterPackage: AdapterPackage): Promise<string[]> {
  const packageKeys = await readMappingScopeKeysFromDir(adapterPackage.dir);
  if (packageKeys.length > 0) {
    return packageKeys;
  }
  const coreMappingDir = join(repoRoot, "packages", "core", "mappings");
  return readMappingScopeKeysFromFiles([join(coreMappingDir, `${adapterPackage.provider}.mapping.yaml`)]);
}

async function readMappingScopeKeysFromDir(packageDir: string): Promise<string[]> {
  const filenames = (await readdir(packageDir)).filter((name) => name.endsWith(".mapping.yaml")).sort();
  return readMappingScopeKeysFromFiles(filenames.map((filename) => join(packageDir, filename)));
}

async function readMappingScopeKeysFromFiles(paths: string[]): Promise<string[]> {
  const keys = new Set<string>();
  for (const path of paths) {
    let contents: string;
    try {
      contents = await readFile(path, "utf8");
    } catch {
      continue;
    }
    const parsed = YAML.parse(contents) as { scopeKeys?: unknown } | null;
    if (!parsed) continue;
    // Accept either a list (`scopeKeys: [owner, repo]`) or a map keyed by name.
    if (Array.isArray(parsed.scopeKeys)) {
      for (const key of parsed.scopeKeys) if (typeof key === "string") keys.add(key);
    } else if (isRecord(parsed.scopeKeys)) {
      for (const key of Object.keys(parsed.scopeKeys)) keys.add(key);
    }
  }
  return [...keys].sort();
}

async function firstExistingPath(paths: string[]): Promise<string | undefined> {
  for (const path of paths) {
    if (await pathExists(path)) {
      return path;
    }
  }
  return undefined;
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

function instantiateAdapter(
  Candidate: new (...args: never[]) => { name?: unknown; supportedScopeKeys(): string[] }
): { name?: unknown; supportedScopeKeys(): string[] } | undefined {
  const client = createClientStub();
  const provider = createProviderStub();
  const attempts: unknown[][] = [
    [client, provider, {}],
    [provider, {}],
    [client, {}],
    [client, provider],
    [provider],
    [client],
    [{}],
    [],
  ];

  for (const args of attempts) {
    try {
      return new Candidate(...(args as never[]));
    } catch {
      // Try the next common adapter constructor shape.
    }
  }

  return undefined;
}

function createClientStub(): Record<string, unknown> {
  return {
    async deleteFile() {
      return undefined;
    },
    getWrittenRevision() {
      return undefined;
    },
    async readFile() {
      return undefined;
    },
    async writeFile() {
      return {};
    },
  };
}

function createProviderStub(): Record<string, unknown> {
  return {
    name: "scope-catalog-generator",
    async proxy() {
      return { status: 200, headers: {}, body: null };
    },
    async healthCheck() {
      return { ok: true };
    },
  };
}

function hasSupportedScopeKeysPrototype(
  value: unknown
): value is new (...args: never[]) => { name?: unknown; supportedScopeKeys(): string[] } {
  return (
    typeof value === "function" &&
    isRecord((value as { prototype?: unknown }).prototype) &&
    typeof (value as { prototype: Record<string, unknown> }).prototype.supportedScopeKeys === "function"
  );
}

function normalizeKeys(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }
  return [...new Set(value.filter((key): key is string => typeof key === "string" && key.length > 0))].sort();
}

function sortCatalog(entries: Array<{ provider: string; keys: string[] }>): ScopeKeyCatalog {
  const catalog = new Map<string, Set<string>>();
  for (const entry of entries) {
    const existing = catalog.get(entry.provider) ?? new Set<string>();
    for (const key of entry.keys) existing.add(key);
    catalog.set(entry.provider, existing);
  }
  return Object.fromEntries(
    [...catalog.entries()]
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([provider, keys]) => [provider, [...keys].sort()])
  );
}

function inferProviderSlug(packageName: string, directoryName: string): string {
  if (packageName.startsWith("@relayfile/adapter-")) {
    return packageName.slice("@relayfile/adapter-".length);
  }
  if (packageName.startsWith("@relayfile/")) {
    return packageName.slice("@relayfile/".length);
  }
  return directoryName;
}

function compareByPackagePath(
  left: { packagePath: string; provider: string },
  right: { packagePath: string; provider: string }
): number {
  return left.packagePath.localeCompare(right.packagePath) || left.provider.localeCompare(right.provider);
}

function renderJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function renderInlineJson(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object";
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
