// Generated by scripts/generate-resource-paths.mjs. Do not edit.
export const POSTHOG_RESOURCE_PATHS = {
  "alert-events": "/posthog/projects/{projectId}/alert-events/{slug}__{eventId}.json",
  "annotations": "/posthog/projects/{projectId}/annotations/{slug}__{annotationId}.json",
  "dashboards": "/posthog/projects/{projectId}/dashboards/{slug}__{dashboardId}.json",
  "experiments": "/posthog/projects/{projectId}/experiments/{slug}__{experimentId}.json",
  "feature-flags": "/posthog/projects/{projectId}/feature-flags/{slug}__{featureFlagId}.json",
  "insights": "/posthog/projects/{projectId}/insights/{slug}__{insightId}.json",
  "projects": "/posthog/projects/{projectId}.json",
  "surveys": "/posthog/projects/{projectId}/surveys/{slug}__{surveyId}.json"
} as const;
