import { literalModelNormalizer, modelBucket } from '@relayfile/adapter-core/sync-bucketing';

export const syncRecordBucketing = modelBucket({
  normalizeModel: literalModelNormalizer({
    RampBill: 'bill',
    bill: 'bill',
    RampPurchaseOrder: 'purchase-order',
    purchaseorder: 'purchase-order',
    'purchase-order': 'purchase-order',
    RampItemReceipt: 'item-receipt',
    itemreceipt: 'item-receipt',
    'item-receipt': 'item-receipt',
    RampVendorAgreement: 'vendor-agreement',
    vendoragreement: 'vendor-agreement',
    'vendor-agreement': 'vendor-agreement',
    RampTransaction: 'transaction',
    transaction: 'transaction',
    RampReimbursement: 'reimbursement',
    reimbursement: 'reimbursement',
    RampReceipt: 'receipt',
    receipt: 'receipt',
    RampVendor: 'vendor',
    vendor: 'vendor',
    RampTransfer: 'transfer',
    transfer: 'transfer',
    RampRepayment: 'repayment',
    repayment: 'repayment',
    RampEntity: 'dimension-entity',
    entity: 'dimension-entity',
    RampUser: 'dimension-user',
    user: 'dimension-user',
    RampDepartment: 'dimension-department',
    department: 'dimension-department',
    RampLocation: 'dimension-location',
    location: 'dimension-location',
    RampMerchant: 'dimension-merchant',
    merchant: 'dimension-merchant',
    RampSpendProgram: 'dimension-spend-program',
    spendprogram: 'dimension-spend-program',
    RampAccountingAccount: 'accounting-account',
    accountingaccount: 'accounting-account',
    RampAccountingField: 'accounting-field',
    accountingfield: 'accounting-field',
    RampBusiness: 'business',
    business: 'business',
  }),
  buckets: {
    'bill': 'bills',
    'purchase-order': 'purchaseOrders',
    'item-receipt': 'itemReceipts',
    'vendor-agreement': 'vendorAgreements',
    'transaction': 'transactions',
    'reimbursement': 'reimbursements',
    'receipt': 'receipts',
    'vendor': 'vendors',
    'transfer': 'transfers',
    'repayment': 'repayments',
    'dimension-entity': 'dimensionEntities',
    'dimension-user': 'dimensionUsers',
    'dimension-department': 'dimensionDepartments',
    'dimension-location': 'dimensionLocations',
    'dimension-merchant': 'dimensionMerchants',
    'dimension-spend-program': 'dimensionSpendPrograms',
    'accounting-account': 'accountingAccounts',
    'accounting-field': 'accountingFields',
    'business': 'businesses',
  },
});
